### PR TITLE
WIP: Add popover

### PR DESCRIPTION
**Pull request by tb**
I started small experiment with "popover" component. I know its not part of MDL, but I think it could be very useful for users as base for building their own advanced components like:
- "tooltips" with HTML markup
- select / multiselect
- date picker / date range picker

So far I was able to make:
- card popover with action buttons
- simple "select"

Let me know what you think about it.

### CODE REVIEW

**Comment by mseemann** [comment]
Hi, thanks for your great work! We need to think and talk about some points before we start additional components. Let me explain: right know the user of angular2-mdl has two opportunities how to use the css. First he just includes a <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css" /> in his index.html and he is done. The second way ist to use the included scss files. These files are a copy of the original material design lite scss sources. If there is a new version of mdl (right now yesterday version 1.2.1 was released) i copy the scss sources to this project by a script. If we add or change the original scss files there are possibly conflicts and the users are loosing the possibilities to just include the css files from the cdn. Right now i have no solution to this problem but some ideas how to solve this:
- avoid adding additional css (difficult and limited)
- create an add-on project that is independent of the material design lite project but could be a collection of additional components that are not already included in material design lite.

What do you think? Let me know!

**Comment by tb** [comment]
Add-on project will be better option. angular2-mdl cloud be peer dependency. Structure of the project could be similar to angular2-mdl.

There are already some projects out there that extend MDL like:
https://github.com/leifoolsen/mdl-ext
https://github.com/Gixx/mdl-components-ext/tree/master/src
https://github.com/trentsp/mdl-datepicker

They usually are named with "-ext" so add-on project could be named angular2-mdl-ext too.

**Comment by mseemann** [comment]
hi. sorry for the late reply - i am on vacation right now.

i also think a angular2-mdl-ext project would be the best solution. This will need some time. And i need to change the build system it is still on the system js version of angular cli.

**Comment by tb** [comment]
Ok. I will continue experiments on this branch. I just pushed quick select/multiselect  Popover/Select/multiselect recodring

**Comment by mseemann** [comment]
i have started the project: https://github.com/mseemann/angular2-mdl-ext. You may see the general setup but it requires still a lot of work for testing and the demo app. I have planned to release every component independent of each other: npm i @angular2-mdl-ext/popover. If you want you can start working there...

**Comment by mseemann** [comment]
further work on it moved to angular2-mdl-ext

**Pull request closed without merging**
