### PR TITLE
WIP - dialog defined in template

### PR DESCRIPTION
**Pull request by tb**
Rename MdlDialogComponent to MdlDialogDefaultComponent
Added MdlDialogComponent for adding dialog defined in template

### CODE REVIEW

**Comment by tb** [comment]
@mseemann I have to try on implementing the https://github.com/mseemann/angular2-mdl/issues/131 `<mdl-dialog #confirmDialog>`. ATM the code only describing some desired behaviour.

The first step seems to be rename the current MdlDialogComponent.

Next step would be to implement the show() / hide() to attach / remove modal using service.  I am not sure how to progress with it.

**Comment by mseemann** [comment]
@tb would you be so kind and add some example for @input and @output attributes and complete the component implementation in the example (app/dialog/dialog.component.html and app/dialog/dialog.component.ts). so that i have a complete example how you want to use the mdl-dialog with the complete api you need? thx!

**Comment by tb** [comment]
@mseemann I think [this](https://github.com/mseemann/angular2-mdl/pull/132/commits/2e2b35e091ca97d1c5e88b749e00814a76b1b989) would be a basic example of data editing modal.

**Comment by mseemann** [comment]
cool thx a lot!

**Comment by mseemann** [comment]
@tb  i'm going to merge this in the master. Just to have the example to work with...

**Pull request merged**
