### PR TITLE
fix(snack-bar): timeout with action in snack-bar

### PR DESCRIPTION
**Pull request by ZafarSaeedKhan**
removed check for timeout and allowed timeout to work in every case

### CODE REVIEW

**Comment by mseemann** [comment]
hi thx for your contribution! first of all it was intended to not close the snackbar automatically. see the docs: 
```
timeout:
for how long should the message be visible. Defaults to 2750 ms. Is ignored if an action is provided.
```

in fact i don't think it is a good usability presenting a button and if the user didn't hit the button do automatically what the button would do. i also want to change this behavior because it would be a breaking change. If you need such a functionality it should be easy to implement this on application level.

**Comment by mseemann** [comment]
some thoughts: 
- it looks to me that this would only work if one snackbar is in progress. but what if there are more than one?
- please avoid property access in this way ['prop']. i prefer to use the typesystem that is provided by typescript. 
- why a static property? the snackbar service is usually a singleton.
- consider adding some test for this feature

**Comment by ZafarSaeedKhan** [comment]
Hello,
Yes i got your point so I revised my implementation and now I can pass a flag to **_closeAfterTimeout_** to close the snackbar after timeout.

Furthermore,
I have implemented your suggestions for consecutive snack bar regarding static variable and the way I used to access property, I also updated the test.
I want to clear that for more than 2 snackbars the 1st one will be in previousSnack variable for the 2nd snackbar and 2nd will be in previousSnack for the 3rd one.
on creation of every snackbar if there is any previousSnack is present then it will hide that then it will show the next one.

**Comment by mseemann** [comment]
closeAfterTimeout as an option sounds great! Did you put both features in the other PR? In this case we should close this one?!

**Comment by mseemann** [comment]
can be closed. right?

**Pull request closed without merging**
